name: 'Filter Pull Requests By Author'
description: 'a github action to filter pull requests by their author and make it available as a matrix'

inputs:
  token:
    description: 'github token'
    default: ${{ github.token }}
  author:  # id of input
    description: 'the author to filter the pull requests by'
    required: true
  state:
    description: 'which pr states to filter'
    required: true
    default: 'open' # closed

outputs:
  ids: # id of output
    description: 'array of pull request ids from the given author'
  html_urls:
    description: 'array of pull request urls from the given author'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'git-pull-request'  
  color: 'blue'
