name: 'Filter Pull Requests By Author'
description: 'a github action to filter pull requests by their author and make it available as a matrix'

inputs:
  token:
    description: 'github token'
    required: true
  author:  # id of input
    description: 'the author to filter the pull requests by'
    required: true 

outputs:
  result: # id of output
    description: 'matrix of pull request ids from the given author'

runs:
  using: 'node16'
  main: 'dist/index.js'